### ISSUE TITLE
内存问题

### ISSUE THREAD

**Issue by ZTurboX** [gotutiyan/gector#1]
用这个项目[cofe-ai/fast-gector](https://github.com/cofe-ai/fast-gector)训练，会出现cpu内存持续增加直至爆掉的情况，请问您这边有遇到吗

**Comment by gotutiyan** [comment]
In my experiences with our implementation, there has been no such problem.

**Comment by ZTurboX** [comment]
support chinese?

**Comment by gotutiyan** [comment]
No. With an appropriate BERT model, the model definition and training scripts could be used in any language.

However, since different languages use different tags, new pre-processing and post-processing scripts are required.
Specifically, for pre-processing, Chinese version of [grammarly/gector/utils/preprocess_data.py](https://github.com/grammarly/gector/blob/master/utils/preprocess_data.py) is needed. For post-processing, please rewrite `edit_src_by_tags()` function in [gotutiyan/gector/predict.py](https://github.com/gotutiyan/gector/blob/3d5c72daf97f76f46111e6e82b6c96f363fc2db0/gector/predict.py#L22) appropriately.

I don't know the detail of Chinese tagging GEC, but [this paper](https://aclanthology.org/2023.findings-acl.370.pdf) could be useful.
